name: Build and Deploy
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  code-review-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check for Code Review Approvals
        run: |
          APPROVALS=$(gh pr review-list --json state \
                       | jq '.[] | select(.state == "APPROVED")' \
                       | wc -l)
          
          if [ $APPROVALS -eq 0 ]; then
            echo "Error: Code review approvals required before merging."
            exit 1
  on: 
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'

env:
  AZURE_WEBAPP_NAME: aspnet-core-sample-deploy  # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './TestBuild'      # set this to the path to your web app project, defaults to the repository root
  NETCORE_VERSION: '7.0.x'                    # set this to the .NET Core version to use

permissions:
  contents: write

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code  
        uses: actions/checkout@v4 
        
      - name: Set up .NET
        uses: xt0rted/setup-dotnet@v1.0.0
        with:
          dotnet-version: ${{ env.NETCORE_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build app
        run: dotnet build -c Release --no-restore

      - name: Publish app for deploy
        run: dotnet publish --configuration Release --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deploy to github pages
        uses: jamesives/github-pages-deploy-action@4.1.0
        with: 
          branch: samplepages
          folder: TestBuild
